import type { AssessmentQuestion } from "../types";

export const mindsetContextQuestions: AssessmentQuestion[] = [
  {
    id: "MC1",
    module: "context",
    type: "single_select",
    text: "Which stream or academic direction are you currently pursuing?",
    options: [
      { id: "science", label: "Science" },
      { id: "commerce", label: "Commerce" },
      { id: "humanities", label: "Humanities" },
      { id: "undecided", label: "Undecided" },
      { id: "other", label: "Other" },
    ],
  },
  {
    id: "MC2",
    module: "context",
    type: "multi_select",
    text: "Which subjects do you genuinely enjoy learning, even without exams?",
    description: "Select all that apply.",
    options: [
      { id: "physics", label: "Physics" },
      { id: "math", label: "Math" },
      { id: "biology", label: "Biology" },
      { id: "psychology", label: "Psychology" },
      { id: "business", label: "Business" },
      { id: "literature", label: "Literature" },
      { id: "cs", label: "Computer Science" },
      { id: "economics", label: "Economics" },
      { id: "design", label: "Design / Art" },
      { id: "political_science", label: "Political Science" },
    ],
  },
  {
    id: "MC3",
    module: "context",
    type: "multi_select",
    text: "Which activities make you lose track of time?",
    description: "Select all that apply.",
    options: [
      { id: "coding_building", label: "Coding / building" },
      { id: "gaming", label: "Gaming" },
      { id: "researching", label: "Researching deeply" },
      { id: "content_creation", label: "Writing / content creation" },
      { id: "public_speaking", label: "Public speaking" },
      { id: "organizing", label: "Organizing events" },
      { id: "designing", label: "Designing / art" },
      { id: "teaching", label: "Teaching / helping people" },
      { id: "problem_solving", label: "Solving difficult problems" },
      { id: "videos", label: "Creating videos / content" },
      { id: "business_ideas", label: "Business ideas / projects" },
    ],
  },
  {
    id: "MC4",
    module: "context",
    type: "multi_select",
    text: "Which subjects do you usually score highest in?",
    description: "Select all that apply.",
    options: [
      { id: "physics", label: "Physics" },
      { id: "math", label: "Math" },
      { id: "biology", label: "Biology" },
      { id: "psychology", label: "Psychology" },
      { id: "business", label: "Business" },
      { id: "literature", label: "Literature" },
      { id: "cs", label: "Computer Science" },
      { id: "economics", label: "Economics" },
      { id: "design", label: "Design / Art" },
      { id: "political_science", label: "Political Science" },
    ],
  },
  {
    id: "MC5",
    module: "context",
    type: "multi_select",
    text: "Which future worlds or industries feel exciting to you right now?",
    description: "Select all that apply.",
    options: [
      { id: "ai_technology", label: "AI & Technology" },
      { id: "entrepreneurship", label: "Entrepreneurship" },
      { id: "psychology", label: "Psychology & Human Behavior" },
      { id: "finance", label: "Finance & Business" },
      { id: "media", label: "Media & Content" },
      { id: "sustainability", label: "Sustainability & Climate" },
      { id: "healthcare", label: "Healthcare & Wellness" },
      { id: "gaming", label: "Gaming & Interactive Media" },
      { id: "design", label: "Design & Creativity" },
      { id: "research", label: "Research & Science" },
      { id: "education", label: "Education & Human Development" },
      { id: "law_policy", label: "Law & Policy" },
      { id: "exploring", label: "Unsure / Exploring" },
    ],
  },
  {
    id: "MC6",
    module: "context",
    type: "single_select",
    text: "What influences your future decisions the most right now?",
    options: [
      { id: "parents", label: "Parents / family expectations" },
      { id: "financial", label: "Financial security" },
      { id: "passion", label: "Personal passion" },
      { id: "prestige", label: "Social status / prestige" },
      { id: "fear", label: "Fear of failure" },
      { id: "freedom", label: "Freedom / flexibility" },
      { id: "impact", label: "Meaning / impact" },
      { id: "confused", label: "I'm honestly confused" },
    ],
  },
  {
    id: "MC7",
    module: "context",
    type: "single_select",
    text: "When making important decisions, what do you usually rely on most?",
    options: [
      { id: "logic", label: "Logic and analysis" },
      { id: "gut", label: "Gut feeling" },
      { id: "advice", label: "Advice from others" },
      { id: "research", label: "Research and comparison" },
      { id: "trying", label: "Trying things directly" },
      { id: "overthink", label: "I overthink and delay decisions" },
    ],
  },
  {
    id: "MC8",
    module: "context",
    type: "single_select",
    text: "What worries you most about your future right now?",
    options: [
      { id: "wrong_career", label: "Choosing the wrong career" },
      { id: "financial", label: "Financial instability" },
      { id: "strengths", label: "Not discovering my real strengths" },
      { id: "family", label: "Letting family down" },
      { id: "falling_behind", label: "Falling behind others" },
      { id: "freedom", label: "Losing freedom" },
      { id: "success", label: "Not being successful enough" },
      { id: "unsure", label: "I honestly don't know what I want" },
    ],
  },
  {
    id: "MC9",
    module: "context",
    type: "single_select",
    text: "Which statement feels closest to your definition of a successful life?",
    options: [
      { id: "meaningful", label: "Building something meaningful" },
      { id: "financial", label: "Becoming financially successful" },
      { id: "freedom", label: "Having freedom and flexibility" },
      { id: "helping", label: "Helping people or society" },
      { id: "respected", label: "Becoming highly respected" },
      { id: "enjoy", label: "Doing work I genuinely enjoy" },
    ],
  },
];
