import type { AssessmentQuestion } from "../types";

export const mirrorContextQuestions: AssessmentQuestion[] = [
  {
    id: "C1",
    module: "context",
    type: "single_select",
    text: "Which grade are you currently in?",
    options: [
      { id: "8", label: "8th" },
      { id: "9", label: "9th" },
      { id: "10", label: "10th" },
    ],
  },
  {
    id: "C2",
    module: "context",
    type: "multi_select",
    text: "Which subjects do you currently enjoy the most?",
    description: "Select all that apply.",
    options: [
      { id: "math", label: "Math" },
      { id: "science", label: "Science" },
      { id: "english", label: "English" },
      { id: "social", label: "Social Science" },
      { id: "computers", label: "Computers" },
      { id: "art", label: "Art" },
      { id: "sports", label: "Sports" },
    ],
  },
  {
    id: "C3",
    module: "context",
    type: "multi_select",
    text: "Which activities do you enjoy outside school?",
    description: "Select all that apply.",
    options: [
      { id: "gaming", label: "Gaming" },
      { id: "drawing_design", label: "Drawing / Design" },
      { id: "building", label: "Building things" },
      { id: "sports", label: "Sports" },
      { id: "reading", label: "Reading" },
      { id: "content_creation", label: "Creating videos / content" },
      { id: "helping", label: "Helping others" },
      { id: "debating", label: "Debating / Public speaking" },
      { id: "coding", label: "Coding / Tech" },
      { id: "music_dance", label: "Music / Dance" },
    ],
  },
  {
    id: "C4",
    module: "context",
    type: "multi_select",
    text: "When you imagine the future, what sounds most exciting to explore?",
    description: "Choose up to 3.",
    maxSelect: 3,
    options: [
      { id: "technology", label: "Technology & Innovation" },
      { id: "business", label: "Business & Leadership" },
      { id: "design", label: "Design & Creativity" },
      { id: "psychology", label: "Psychology & Human Behavior" },
      { id: "science", label: "Science & Research" },
      { id: "media", label: "Media & Communication" },
      { id: "engineering", label: "Building / Engineering" },
      { id: "helping", label: "Helping & Teaching People" },
      { id: "sustainability", label: "Nature & Sustainability" },
    ],
  },
  {
    id: "C5",
    module: "context",
    type: "single_select",
    text: 'Have you already been told what career you "should" choose?',
    options: [
      { id: "strongly", label: "Yes, very strongly" },
      { id: "sometimes", label: "Sometimes" },
      { id: "not_really", label: "Not really" },
      { id: "unsure", label: "I'm not sure yet" },
    ],
  },
  {
    id: "C6",
    module: "context",
    type: "single_select",
    text: "How clear do you currently feel about your future?",
    options: [
      { id: "very_clear", label: "Very clear" },
      { id: "somewhat", label: "Somewhat clear" },
      { id: "confused", label: "Confused" },
      { id: "curious", label: "Very confused but curious" },
    ],
  },
  {
    id: "C7",
    module: "context",
    type: "single_select",
    text: "Which statement feels closest to you right now?",
    options: [
      { id: "know", label: "I already know what I want to pursue" },
      { id: "many_interests", label: "I have many interests and can't decide" },
      { id: "follow_others", label: "I mostly follow what others suggest" },
      { id: "discovering", label: "I'm still discovering myself" },
    ],
  },
  {
    id: "C8",
    module: "context",
    type: "single_select",
    text: "What do you hope Marga helps you with the most?",
    options: [
      { id: "understand", label: "Understanding myself better" },
      { id: "direction", label: "Finding career direction" },
      { id: "strengths", label: "Discovering strengths" },
      { id: "reduce_confusion", label: "Reducing confusion" },
      { id: "explore", label: "Exploring new possibilities" },
    ],
  },
];
