import type { AssessmentQuestion } from "../types";

const motivationQuestions: AssessmentQuestion[] = [
  {
    id: "M_Q1",
    module: "motivation",
    type: "single_select",
    text: "Which activity would you most willingly spend your free day doing?",
    options: [
      { id: "a", label: "Building or creating something new", signals: { builder: 4 } },
      { id: "b", label: "Leading a group activity", signals: { leader: 4 } },
      { id: "c", label: "Learning deeply about an interesting topic", signals: { thinker: 4 } },
      { id: "d", label: "Helping someone solve a problem", signals: { guide: 4 } },
    ],
  },
  {
    id: "M_Q2",
    module: "motivation",
    type: "single_select",
    text: "Which type of success feels most meaningful to you?",
    options: [
      { id: "a", label: "Inventing something original", signals: { creator: 4 } },
      { id: "b", label: "Being respected as a leader", signals: { leader: 4 } },
      { id: "c", label: "Becoming highly skilled at something", signals: { thinker: 4 } },
      { id: "d", label: "Making a positive difference in people's lives", signals: { guide: 4 } },
    ],
  },
  {
    id: "M_Q3",
    module: "motivation",
    type: "single_select",
    text: "If nobody judged you, what would you most love spending years getting really good at?",
    options: [
      { id: "a", label: "Creating things", signals: { creator: 4 } },
      { id: "b", label: "Solving hard problems", signals: { thinker: 4 } },
      { id: "c", label: "Leading or influencing people", signals: { leader: 4 } },
      { id: "d", label: "Supporting or guiding others", signals: { guide: 4 } },
    ],
  },
  {
    id: "M_Q4",
    module: "motivation",
    type: "likert",
    text: "I feel energized when I discover something new on my own.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { builder: 1, thinker: 1 },
      { builder: 2, thinker: 1 },
      { builder: 3, thinker: 1 },
      { builder: 3, thinker: 1 },
    ],
  },
  {
    id: "M_Q5",
    module: "motivation",
    type: "likert",
    text: "I enjoy taking responsibility in group situations.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { leader: 1, builder: 1 },
      { leader: 2, builder: 1 },
      { leader: 3, builder: 1 },
      { leader: 4, builder: 1 },
    ],
  },
  {
    id: "M_Q6",
    module: "motivation",
    type: "likert",
    text: "Helping others succeed feels important to me.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { guide: 1, leader: 1 },
      { guide: 2, leader: 1 },
      { guide: 3, leader: 1 },
      { guide: 4, leader: 1 },
    ],
  },
  {
    id: "M_Q7",
    module: "motivation",
    type: "single_select",
    text: "Your school announces a month-long innovation challenge. Which role sounds most exciting?",
    options: [
      { id: "a", label: "Generating creative ideas", signals: { creator: 4 } },
      { id: "b", label: "Planning and managing the team", signals: { leader: 4 } },
      { id: "c", label: "Solving technical/logical problems", signals: { thinker: 4 } },
      { id: "d", label: "Presenting and communicating the idea", signals: { creator: 2, leader: 2 } },
    ],
  },
  {
    id: "M_Q8",
    module: "motivation",
    type: "single_select",
    text: "You are starting a completely new project with friends. What naturally matters most to you?",
    options: [
      { id: "a", label: "Making it exciting and original", signals: { creator: 4 } },
      { id: "b", label: "Making sure it succeeds", signals: { builder: 3, leader: 1 } },
      { id: "c", label: "Making everyone feel involved", signals: { guide: 4 } },
      { id: "d", label: "Making it meaningful or useful", signals: { guide: 3, thinker: 1 } },
    ],
  },
  {
    id: "M_Q9",
    module: "motivation",
    type: "rank",
    text: "Rank these from MOST motivating (1) to LEAST motivating (5):",
    rankItems: [
      { id: "recognition", label: "Winning recognition", archetype: "leader" },
      { id: "challenges", label: "Solving difficult challenges", archetype: "thinker" },
      { id: "helping", label: "Helping people", archetype: "guide" },
      { id: "creating", label: "Creating something original", archetype: "creator" },
      { id: "learning", label: "Learning something fascinating", archetype: "builder" },
    ],
  },
];

const abilityQuestions: AssessmentQuestion[] = [
  {
    id: "A_Q1",
    module: "ability",
    type: "single_select",
    text: "Which type of task feels easiest for you naturally?",
    options: [
      { id: "a", label: "Explaining ideas to people", signals: { leader: 4 } },
      { id: "b", label: "Solving difficult problems", signals: { thinker: 4 } },
      { id: "c", label: "Creating designs, art, or visuals", signals: { creator: 4 } },
      { id: "d", label: "Organizing work or planning things", signals: { builder: 4 } },
    ],
  },
  {
    id: "A_Q2",
    module: "ability",
    type: "single_select",
    text: "Which activity do you usually learn the fastest?",
    options: [
      { id: "a", label: "Building or making things", signals: { builder: 4 } },
      { id: "b", label: "Understanding systems and patterns", signals: { thinker: 4 } },
      { id: "c", label: "Communicating ideas creatively", signals: { creator: 4 } },
      { id: "d", label: "Working with people in teams", signals: { guide: 2, leader: 2 } },
    ],
  },
  {
    id: "A_Q3",
    module: "ability",
    type: "single_select",
    text: "If your teacher gave a completely open-ended project, what would you most likely focus on first?",
    options: [
      { id: "a", label: "Creativity and originality", signals: { creator: 4 } },
      { id: "b", label: "Accuracy and logic", signals: { thinker: 4 } },
      { id: "c", label: "Leadership and coordination", signals: { leader: 4 } },
      { id: "d", label: "Making it visually impressive", signals: { creator: 3, builder: 1 } },
    ],
  },
  {
    id: "A_Q4",
    module: "ability",
    type: "likert",
    text: "I notice patterns and connections quickly.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { thinker: 1, builder: 1 },
      { thinker: 2, builder: 1 },
      { thinker: 3, builder: 1 },
      { thinker: 4, builder: 1 },
    ],
  },
  {
    id: "A_Q5",
    module: "ability",
    type: "likert",
    text: "I enjoy expressing ideas visually or creatively.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { creator: 1, guide: 1 },
      { creator: 2, guide: 1 },
      { creator: 3, guide: 1 },
      { creator: 4, guide: 1 },
    ],
  },
  {
    id: "A_Q6",
    module: "ability",
    type: "likert",
    text: "I naturally think about improving how things work.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { builder: 1, thinker: 1 },
      { builder: 2, thinker: 1 },
      { builder: 3, thinker: 1 },
      { builder: 4, thinker: 1 },
    ],
  },
  {
    id: "A_Q7",
    module: "ability",
    type: "single_select",
    text: "Your team's plan is messy and confusing. What would you most likely do first?",
    options: [
      { id: "a", label: "Create a clear structure or plan", signals: { thinker: 2, builder: 2 } },
      { id: "b", label: "Build a quick solution to test ideas", signals: { builder: 4 } },
      { id: "c", label: "Explain things clearly to everyone", signals: { leader: 4 } },
      { id: "d", label: "Suggest a creative new direction", signals: { creator: 4 } },
    ],
  },
  {
    id: "A_Q8",
    module: "ability",
    type: "single_select",
    text: "You are given random materials for a school challenge. What excites you most?",
    options: [
      { id: "a", label: "Experimenting with ideas", signals: { builder: 3, creator: 1 } },
      { id: "b", label: "Solving the challenge efficiently", signals: { thinker: 4 } },
      { id: "c", label: "Designing something visually interesting", signals: { creator: 4 } },
      { id: "d", label: "Collaborating with the group", signals: { guide: 3, leader: 1 } },
    ],
  },
  {
    id: "A_Q9",
    module: "ability",
    type: "rank",
    text: "Rank these from MOST enjoyable (1) to LEAST enjoyable (5):",
    rankItems: [
      { id: "puzzles", label: "Solving puzzles/problems", archetype: "thinker" },
      { id: "creative", label: "Creating art/content/designs", archetype: "creator" },
      { id: "leadership", label: "Leading a group activity", archetype: "leader" },
      { id: "building", label: "Building or making things", archetype: "builder" },
      { id: "helping", label: "Helping people learn or improve", archetype: "guide" },
    ],
  },
];

const resilienceQuestions: AssessmentQuestion[] = [
  {
    id: "R_Q1",
    module: "resilience",
    type: "single_select",
    text: "When something becomes very difficult, what do you usually do first?",
    options: [
      { id: "a", label: "Keep trying different solutions", signals: { builder: 4 } },
      { id: "b", label: "Step back and think carefully", signals: { thinker: 4 } },
      { id: "c", label: "Ask others for help or support", signals: { guide: 4 } },
      { id: "d", label: "Distract myself and move on", signals: { creator: 1 } },
    ],
  },
  {
    id: "R_Q2",
    module: "resilience",
    type: "single_select",
    text: "What usually motivates you to continue after failure?",
    options: [
      { id: "a", label: "Wanting to prove I can improve", signals: { builder: 4 } },
      { id: "b", label: "Curiosity to understand what went wrong", signals: { thinker: 4 } },
      { id: "c", label: "Support from others", signals: { guide: 4 } },
      { id: "d", label: "Wanting to achieve something meaningful", signals: { guide: 2, leader: 2 } },
    ],
  },
  {
    id: "R_Q3",
    module: "resilience",
    type: "single_select",
    text: 'If a project you worked hard on fails badly, what would you most likely think?',
    options: [
      { id: "a", label: "I should try a better approach.", signals: { builder: 4 } },
      { id: "b", label: "I want to understand why it failed.", signals: { thinker: 4 } },
      { id: "c", label: "Maybe I need more support or teamwork.", signals: { guide: 4 } },
      { id: "d", label: "Maybe I'm just not good at this.", signals: {} },
    ],
  },
  {
    id: "R_Q4",
    module: "resilience",
    type: "likert",
    text: "I can stay calm and focused even when things don't go as planned.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { builder: 1, thinker: 1 },
      { builder: 1, thinker: 1, leader: 1 },
      { builder: 2, thinker: 2, leader: 1 },
      { builder: 2, thinker: 2, leader: 1 },
    ],
  },
  {
    id: "R_Q5",
    module: "resilience",
    type: "likert",
    text: "I usually learn something useful from mistakes.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { thinker: 1, builder: 1 },
      { thinker: 2, builder: 1 },
      { thinker: 2, builder: 2 },
      { thinker: 3, builder: 2 },
    ],
  },
  {
    id: "R_Q6",
    module: "resilience",
    type: "likert",
    text: "I can recover quickly after feeling disappointed.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { leader: 1, guide: 1 },
      { leader: 2, guide: 1 },
      { leader: 2, guide: 2 },
      { leader: 3, guide: 2 },
    ],
  },
  {
    id: "R_Q7",
    module: "resilience",
    type: "single_select",
    text: "Your team suddenly faces a major problem before a competition deadline. What would you most likely do?",
    options: [
      { id: "a", label: "Quickly try practical solutions", signals: { builder: 4 } },
      { id: "b", label: "Analyze the problem carefully", signals: { thinker: 4 } },
      { id: "c", label: "Encourage and support the team", signals: { guide: 4 } },
      { id: "d", label: "Suggest a creative alternative approach", signals: { creator: 4 } },
    ],
  },
  {
    id: "R_Q8",
    module: "resilience",
    type: "single_select",
    text: "You have to learn a completely new skill for school. What is your natural reaction?",
    options: [
      { id: "a", label: "Excited to experiment and try", signals: { builder: 4 } },
      { id: "b", label: "Curious to understand how it works", signals: { thinker: 4 } },
      { id: "c", label: "Nervous but willing to ask for help", signals: { guide: 3, leader: 1 } },
      { id: "d", label: "Worried I may not do well", signals: {} },
    ],
  },
  {
    id: "R_Q9",
    module: "resilience",
    type: "rank",
    text: "Rank these from MOST important (1) to LEAST important (5) when facing challenges:",
    rankItems: [
      { id: "calm", label: "Staying calm", archetype: "leader" },
      { id: "quick", label: "Solving the problem quickly", archetype: "builder" },
      { id: "learning", label: "Learning from mistakes", archetype: "thinker" },
      { id: "support", label: "Asking for support", archetype: "guide" },
      { id: "creative", label: "Trying a creative new approach", archetype: "creator" },
    ],
  },
];

const goalsQuestions: AssessmentQuestion[] = [
  {
    id: "G_Q1",
    module: "goals",
    type: "single_select",
    text: "Which type of future feels most exciting to you?",
    options: [
      { id: "a", label: "Building new technology or products", signals: { builder: 4 } },
      { id: "b", label: "Understanding complex ideas deeply", signals: { thinker: 4 } },
      { id: "c", label: "Creating something original that people enjoy", signals: { creator: 4 } },
      { id: "d", label: "Helping people grow or improve", signals: { guide: 4 } },
    ],
  },
  {
    id: "G_Q2",
    module: "goals",
    type: "single_select",
    text: "What would make you feel most successful in the future?",
    options: [
      { id: "a", label: "Creating something useful or innovative", signals: { builder: 4 } },
      { id: "b", label: "Becoming highly knowledgeable or skilled", signals: { thinker: 4 } },
      { id: "c", label: "Inspiring or influencing many people", signals: { leader: 4 } },
      { id: "d", label: "Making a meaningful difference in others' lives", signals: { guide: 4 } },
    ],
  },
  {
    id: "G_Q3",
    module: "goals",
    type: "single_select",
    text: "If you could spend years mastering one area, what would you choose?",
    options: [
      { id: "a", label: "Technology or engineering", signals: { builder: 4 } },
      { id: "b", label: "Psychology, science, or research", signals: { thinker: 4 } },
      { id: "c", label: "Art, storytelling, or design", signals: { creator: 4 } },
      { id: "d", label: "Leadership, business, or teamwork", signals: { leader: 4 } },
    ],
  },
  {
    id: "G_Q4",
    module: "goals",
    type: "likert",
    text: "I often think seriously about the future I want to create.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { builder: 1, leader: 1 },
      { builder: 2, leader: 1 },
      { builder: 2, leader: 2 },
      { builder: 3, leader: 2 },
    ],
  },
  {
    id: "G_Q5",
    module: "goals",
    type: "likert",
    text: "I want my future work to reflect who I truly am.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { creator: 1, guide: 1 },
      { creator: 2, guide: 1 },
      { creator: 2, guide: 2 },
      { creator: 3, guide: 2 },
    ],
  },
  {
    id: "G_Q6",
    module: "goals",
    type: "likert",
    text: "I enjoy setting goals and working steadily toward them.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { leader: 1, builder: 1 },
      { leader: 2, builder: 1 },
      { leader: 2, builder: 2 },
      { leader: 3, builder: 2 },
    ],
  },
  {
    id: "G_Q7",
    module: "goals",
    type: "single_select",
    text: "Your school gives you a chance to work on a real-world future project. Which sounds most exciting?",
    options: [
      { id: "a", label: "Building a useful app or invention", signals: { builder: 4 } },
      { id: "b", label: "Researching a complex social/scientific problem", signals: { thinker: 4 } },
      { id: "c", label: "Creating a campaign, film, or design project", signals: { creator: 4 } },
      { id: "d", label: "Leading a community or school initiative", signals: { leader: 4 } },
    ],
  },
  {
    id: "G_Q8",
    module: "goals",
    type: "single_select",
    text: "Imagine your ideal future work environment. What feels most exciting?",
    options: [
      { id: "a", label: "Fast-moving and innovative", signals: { builder: 4 } },
      { id: "b", label: "Calm and intellectually challenging", signals: { thinker: 4 } },
      { id: "c", label: "Creative and expressive", signals: { creator: 4 } },
      { id: "d", label: "Collaborative and people-focused", signals: { guide: 4 } },
    ],
  },
  {
    id: "G_Q9",
    module: "goals",
    type: "rank",
    text: "Rank these future priorities from MOST important (1) to LEAST important (5):",
    rankItems: [
      { id: "building", label: "Building something meaningful", archetype: "builder" },
      { id: "skill", label: "Becoming highly skilled", archetype: "thinker" },
      { id: "creativity", label: "Expressing creativity", archetype: "creator" },
      { id: "leadership", label: "Leading or influencing others", archetype: "leader" },
      { id: "helping", label: "Helping people grow", archetype: "guide" },
    ],
  },
];

const awarenessQuestions: AssessmentQuestion[] = [
  {
    id: "AW_Q1",
    module: "awareness",
    type: "single_select",
    text: "Which description feels most like you naturally?",
    options: [
      { id: "a", label: "I enjoy building or improving things", signals: { builder: 4 } },
      { id: "b", label: "I enjoy understanding ideas deeply", signals: { thinker: 4 } },
      { id: "c", label: "I enjoy expressing myself creatively", signals: { creator: 4 } },
      { id: "d", label: "I enjoy helping or guiding people", signals: { guide: 4 } },
    ],
  },
  {
    id: "AW_Q2",
    module: "awareness",
    type: "single_select",
    text: "What do people usually appreciate most about you?",
    options: [
      { id: "a", label: "My practical problem-solving", signals: { builder: 4 } },
      { id: "b", label: "My intelligence or ideas", signals: { thinker: 4 } },
      { id: "c", label: "My creativity or originality", signals: { creator: 4 } },
      { id: "d", label: "My supportiveness or kindness", signals: { guide: 4 } },
    ],
  },
  {
    id: "AW_Q3",
    module: "awareness",
    type: "single_select",
    text: "Which area do you most want to improve in yourself?",
    options: [
      { id: "a", label: "Becoming more disciplined and focused", signals: { builder: 3 } },
      { id: "b", label: "Becoming more confident speaking or leading", signals: { leader: 4 } },
      { id: "c", label: "Becoming more creative or expressive", signals: { creator: 4 } },
      { id: "d", label: "Becoming better at understanding people", signals: { guide: 4 } },
    ],
  },
  {
    id: "AW_Q4",
    module: "awareness",
    type: "likert",
    text: "I understand my strengths and weaknesses clearly.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { thinker: 1, guide: 1 },
      { thinker: 2, guide: 1 },
      { thinker: 2, guide: 2 },
      { thinker: 3, guide: 2 },
    ],
  },
  {
    id: "AW_Q5",
    module: "awareness",
    type: "likert",
    text: "I think carefully before making important decisions.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { thinker: 1, leader: 1 },
      { thinker: 2, leader: 1 },
      { thinker: 3, leader: 1 },
      { thinker: 4, leader: 1 },
    ],
  },
  {
    id: "AW_Q6",
    module: "awareness",
    type: "likert",
    text: "I notice how my actions or words affect other people.",
    likertMinLabel: "Strongly disagree",
    likertMaxLabel: "Strongly agree",
    likertSignals: [
      {},
      { guide: 1, leader: 1 },
      { guide: 2, leader: 1 },
      { guide: 3, leader: 1 },
      { guide: 4, leader: 1 },
    ],
  },
  {
    id: "AW_Q7",
    module: "awareness",
    type: "single_select",
    text: "Your friend group has a misunderstanding and tension is rising. What would you most likely do?",
    options: [
      { id: "a", label: "Try solving the issue practically", signals: { builder: 4 } },
      { id: "b", label: "Step back and understand both sides", signals: { thinker: 4 } },
      { id: "c", label: "Help everyone feel heard and calmer", signals: { guide: 4 } },
      { id: "d", label: "Suggest a creative or different way forward", signals: { creator: 4 } },
    ],
  },
  {
    id: "AW_Q8",
    module: "awareness",
    type: "single_select",
    text: "You receive unexpected criticism about something important to you. What is your first natural reaction?",
    options: [
      { id: "a", label: "Improve and prove myself through action", signals: { builder: 4 } },
      { id: "b", label: "Reflect deeply on whether it is true", signals: { thinker: 4 } },
      { id: "c", label: "Feel emotionally affected for some time", signals: { creator: 3, guide: 1 } },
      { id: "d", label: "Ask questions to understand the feedback better", signals: { guide: 3, thinker: 1 } },
    ],
  },
  {
    id: "AW_Q9",
    module: "awareness",
    type: "rank",
    text: "Rank these from MOST important (1) to LEAST important (5) in understanding yourself better:",
    rankItems: [
      { id: "strengths", label: "Knowing your strengths", archetype: "builder" },
      { id: "emotions", label: "Understanding your emotions", archetype: "guide" },
      { id: "weaknesses", label: "Improving your weaknesses", archetype: "thinker" },
      { id: "perception", label: "Understanding how others see you", archetype: "leader" },
      { id: "meaning", label: "Discovering what truly matters to you", archetype: "creator" },
    ],
  },
];

export const mirrorMargaQuestions: AssessmentQuestion[] = [
  ...motivationQuestions,
  ...abilityQuestions,
  ...resilienceQuestions,
  ...goalsQuestions,
  ...awarenessQuestions,
];

export {
  motivationQuestions,
  abilityQuestions,
  resilienceQuestions,
  goalsQuestions,
  awarenessQuestions,
};
